version: "3.8"
services:
  tutor-db:
    container_name: tutor-db
    restart: always
    image: postgres:15.4-alpine3.18
    ports:
      - "5222:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tutorSecret
      POSTGRES_DB: tutor